import 'package:flutter/material.dart';
import 'core/theme/app_theme.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart'; // generated by: flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const BricklackApp());
}

class BricklackApp extends StatelessWidget {
  const BricklackApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bricklack',
      theme: AppTheme.light,
      debugShowCheckedModeBanner: false,
      home: const Scaffold(
        body: Center(
          child: Text('Bricklack Mobile'),
        ),
      ),
    );
  }
}
